# -*- coding: utf-8 -*-
"""JGRMLC_MAUNet_Light_Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLXpba2_c1kIqOoP0Hejx1c_PTNdKSqi
"""

import tensorflow as tf
import keras
from tensorflow.keras.utils import plot_model

#MAUNet Light

IMG_WIDTH = None
IMG_HEIGHT = None
IMG_CHANNELS = 1

#Build the model
inputs = tf.keras.layers.Input((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))

c1 = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(inputs)
c1 = tf.keras.layers.Dropout(0.3)(c1)
c1 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c1)
p1 = tf.keras.layers.MaxPooling2D((2, 2))(c1)
a1 = tf.keras.layers.AveragePooling2D((2,2))(c1)

c2 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p1)
c2 = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')((p1+c2)*0.5)
c2 = tf.keras.layers.Dropout(0.2)(c2)
c2 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')((c2+a1)*0.5)

u5 = tf.keras.layers.Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same')(c2)
u5 = tf.keras.layers.concatenate([(u5+inputs)*0.5, c1])
c5 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u5)
c5 = tf.keras.layers.Dropout(0.1)(c5)
c5 = tf.keras.layers.Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c5)

outputs = tf.keras.layers.Conv2D(1, (1, 1), activation='relu')(c5)

Student_Model = tf.keras.Model(inputs=[inputs], outputs=[outputs])
Student_Model.compile(optimizer='adam', loss='mean_squared_error')
Student_Model.summary()
plot_model(Student_Model, show_shapes=True)

#Set EarlyStopping Criteria
earlystop=tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    min_delta=0,
    patience=20,
    verbose=0,
    mode='min',
    baseline=None,
    restore_best_weights=True
  )
checkpoint=tf.keras.callbacks.ModelCheckpoint(
    filepath="checkmodel.keras",
    monitor='val_loss',
    verbose=1,
    mode='min',
    save_best_only= True,
    )